### ISSUE TITLE
The default value of "recurrent" field in Task model

### ISSUE THREAD

**Issue by ChanwooLucioLee** [swsnu/swpp2020-team13#1]
What is the default value of "recurrent" field in Task model supposed to be? True or False?
What would be a more common case?

In fact, we can indicate that some task is not recurrent by setting day_of_week field as "NONE."
Do we still need this field? Would it be better to leave it or not?

**Comment by jiyewise** [comment]
I think that makes a point. If there is 'None' field, I think deleting the recurrent field would be fine. I will reflect this in my CRUD implementation. :)

**Comment by ChanwooLucioLee** [comment]
@jiyewise Okay, let's delete it.
