### ISSUE TITLE
URL formatting

### ISSUE THREAD

**Issue by songbird39** [swsnu/swpp2020-team13#10]
As far as I remember, the URL formatting of our pages was not decided. It should have been discussed before sprint 2, but I guess our minds were too busy at that time. When I tried to find our previous decisions, I discovered some inconsistencies in our documents.

Below is what our first few sections say:
- Intro page (/)
- Main board (goals) page (/main)
- Dashboard page (/dashboard)
  - Goal-detail-page (/dashboard/{:goal_id})
- Explore page (/explore)
- Profile page (/profile)
  - Edit-profile-page (/profile/edit)

and following is what our Frontend Component per page section says:
- Intro page (/)
- Main board (goals) page (/**<:username>**/main)
- Dashboard page (/**<:username>**/dashboard)
  - Goal-detail-page (/**<:username>**/dashboard/{:goal_id})
- Explore page (/explore)
- Profile page (/**<:username>**/profile)

It seems that we haven't done any proper discussion after TA feedback, and didn't arrive at any agreement regarding this issue. This may be a long talk to have here so I will bring this up at our meeting tonight. (This issue is for the record.)

**Comment by ChanwooLucioLee** [comment]
I think the second one looks good. Then we will need to ensure that username is unique.
Also, if a user changes her username, then some links should break. I'm not sure if that's what we are okay with.
