### ISSUE TITLE
Daily Goal View: UI/UX topics

### ISSUE THREAD

**Issue by songbird39** [swsnu/swpp2020-team13#11]
By "Daily Goal View" I mean the former "Today's Goals" section, where we decided to change the title text to today's date, since a new date may be selected from the calendar. It is just a name I made up just now.
I am weighing with some design choices related to UI/UX here, and would like to address some of them.

1. What goals should we display?
Some goals would have no tasks to address now. Should we display them as well? (My opinion now is yes, since we can add tasks in this daily goal page, it should be here ready to be added any task)

2. In what order?
For the tasks, it would be logical to sort them by importance, but how about the goals? These are my ideas now:
   1. Sort by pending: the end date of the goal is nearest
   2. Sort alphabetically
   3. Sort by goal creation date: newest first / oldest first
   3. Sort by most important task: this might be confusing when the order changes every day
   4. Let the user set the importance of the goal as well
   5. Let users drag & drop the goals to reorder them, and save it for the next session & days: This is what I prefer for now, but the implementation may be overly difficult for a class project?

**Comment by ChanwooLucioLee** [comment]
1. We can display a full list of goals. 

2. Default: Sort by goal creation date: newest first / oldest first. Also, there will be a button to sort by date
   On top of that, let users drag & drop the goals to reorder them.
   I'm considering letting users set the importance of the goal but let's keep it simple for the time being.
