### ISSUE TITLE
Allow Partial Update or Not

### ISSUE THREAD

**Issue by ChanwooLucioLee** [swsnu/swpp2020-team13#2]
We are allowing only PUT but not PATCH.
Are we going to allow partial updates with PUT method, which is not the default behavior?

**Comment by jiyewise** [comment]
I didn't know there was a 'PATCH' type of request. What is the difference between 'PUT' and 'PATCH', and what would the syntax for PATCH be? Could you explain more please?

**Comment by ChanwooLucioLee** [comment]
@jiyewise 
Suppose a signature of User model is { id: number, name: string, age: number } and you are trying to update an instance { id: 1, name: "Jiye", age: 23 }

PUT request with { name: "Jiye" } to the instance will result in { id: 1, name: "Jiye", age: blank } because PUT replace the old with the new. For the same token, PUT request with { age: 99 } to the instance will result in { id: 1, name: blank, age: 99 }. If age or name field are required, the request will probably fail.

However, PATCH request with { name: "Jiye" } to the instance will result in { id: 1, name: "Jiye", age: 23 } because it's doing partial update.

**Comment by jiyewise** [comment]
I think PATCH would be a good idea..! What would the syntax of PATCH be? Could you give a simple example (of codes)? As soon as I catch up with the syntax, I will reflect it on my implementation.

**Comment by ChanwooLucioLee** [comment]
@jiyewise The syntax for PATCH is very similar to PUT except you don't need to specify all fields.
PUT: axios.put(...)
PATCH: axios.patch(...)

**Comment by jiyewise** [comment]
@ChanwooLucioLee Oh, then there is no difference of implementation in django?

**Comment by ChanwooLucioLee** [comment]
@jiyewise It looks like Django isn't designed to handle a partial update of an arbitrary subset of fields on the model. You might need to handle it manually unless you use extra library such as Django Rest Framework.

**Comment by songbird39** [comment]
I personally prefer using PUT to handle all requests... but maybe it is because I don't really know what benefit PATCH has. Plus, when you press edit, don't the text area already include the former data by default? I wonder if that makes any difference to the PUT vs PATCH issue?

**Comment by ChanwooLucioLee** [comment]
@songbird39 You are making sense. I agree with you.
