### ISSUE TITLE
Deadline field for Goal or Task

### ISSUE THREAD

**Issue by ChanwooLucioLee** [swsnu/swpp2020-team13#3]
Goal model has deadline field but Task model does not.
What makes more sense between a goal or tasks having a deadline?

**Comment by jiyewise** [comment]
I was about to leave a similar comment regarding deadline of goals :)
Regarding your question, my original idea was to fetch the deadline data from the goal. **However, I guess implementing deadline field in tasks also (both in goal and task) would be better**, as users may want to follow certain tasks only for a short period of time. When deadline for task does not come in as input, it can set default deadline as the goal deadline.
**In this case, I think there should be a restriction that the task deadline should not go over the goal deadline**. When the task deadline goes over the goals', then it would be set to the goal deadline with an alert.

**Comment by ChanwooLucioLee** [comment]
@jiyewise Okay. You're saying that both Goal and Task will have their own deadline but a Task's deadline cannot be later than its Goal's deadline. I agree.
