### ISSUE TITLE
Hitting the explore button redirects to a blank page

### ISSUE THREAD

**Issue by songbird39** [swsnu/swpp2020-team13#31]
How to produce the bug: When the account is first created & redirected to the main page, click the explore button.

The explore page is displayed for a short moment, but then becomes a blank page.

**Comment by jiyewise** [comment]
빈 페이지라는게 menu bar는 보이는 페이지인가요? 사진을 첨부해 주세요

**Comment by songbird39** [comment]
+) After creating a goal, the explore page is rendered properly.

**Comment by songbird39** [comment]
![image](https://user-images.githubusercontent.com/50364722/101653226-73545c00-3a82-11eb-9568-f2ba19da7866.png)
아예 빈 백지 페이지입니다.

**Comment by jiyewise** [comment]
일단 제가 로컬에서 새 계정 만들고 바로 explore 클릭했을 때는 정상적으로 작동합니다 deploy가 엮이면서 생긴 버그같은데 지금은 해결이 힘들 것 같네요
![image](https://user-images.githubusercontent.com/67668461/101653439-adbdf900-3a82-11eb-80de-5b67702805c1.png)

**Comment by jiyewise** [comment]
프론트 관련 bug인 거 같아서 우선 수정하고 다시 푸시했습니다

**Comment by songbird39** [comment]
![image](https://user-images.githubusercontent.com/50364722/101656215-cf6caf80-3a85-11eb-9198-ff1bc1d9e244.png)
현재 이미 goal이 있는 유저로 로그인 했을 때도 같은 문제가 있음을 확인했습니다.

**Comment by jiyewise** [comment]
photo가 null일 경우 핸들링이 안되는 문제였고 다시 수정했습니다. 크롬 프로그램 종료후 다시 재시작하고 goalingball.com 들어가면 이제 정상작동합니다.

**Comment by songbird39** [comment]
네 정상 작동 확인했습니다
