### ISSUE TITLE
All tasks are displayed, regardless of the day of the week settings

### ISSUE THREAD

**Issue by songbird39** [swsnu/swpp2020-team13#34]
How to generate the bug:
Create any goal, then create any task that is repetitive with the days of the week setting.

What was expected:
1) The tasks for today should be displayed for default, then when the "Show all tasks" button is toggled on, other tasks should be shown as well
or
2) **Only the goal name should be displayed for default, then when the "Show all tasks" button is toggled on, the tasks for today should be displayed.**

What happened:
No tasks are displayed for default, then when the "Show all tasks" button is toggled on, all tasks are displayed, including the tasks not for today.

**Comment by jiyewise** [comment]
애초에 버그가 아니라 show all task들은 해당 날짜와 요일에 상관없는 task들을 보여주기 위한 버튼입니다
