### ISSUE TITLE
In dashboard-goal detail page, the task importance is not displayed properly

### ISSUE THREAD

**Issue by songbird39** [swsnu/swpp2020-team13#36]
This is a relatively minor bug:
On the dashboard-goal detail page, the task importance reacts when the mouse is over the importance stars, as if it can be edited. However, clicking on it doesn't trigger anything, and the task importance remains the same.

(edit) the console doesn't have any output for this error.

**Comment by jiyewise** [comment]
readOnly property 가 누락되어 있어서 추가했습니다
