### ISSUE TITLE
Task title checkmark issues

### ISSUE THREAD

**Issue by songbird39** [swsnu/swpp2020-team13#39]
![image](https://user-images.githubusercontent.com/50364722/101658917-d812b500-3a88-11eb-864e-efcb36ad1f04.png)
![image](https://user-images.githubusercontent.com/50364722/101658972-e791fe00-3a88-11eb-9549-715ad20d8b5a.png)
The checkmark doesn't show when first displaying the goal detail page, so it is difficult to find where to click to see the task details. Then after clicking, the checkmark doesn't disappear when another task is selected.

Suggested improvements:
1) show all checkmarks anytime (+ optional: display red checkmark for the selected task)
2) show the task details when the task title is clicked, and display checkmark only for the selected task

**Comment by jiyewise** [comment]
원래는 디폴트로 체크마크가 항상 뜨는데 호환성 문제인가 싶네요

**Comment by songbird39** [comment]
참고로 추가하자면 윈도우 상에서 크롬 사용중입니다!

**Comment by jiyewise** [comment]
css 호환성 문제여서 수정했습니다
