### ISSUE TITLE
API for adding and deleting tags

### ISSUE THREAD

**Issue by ChanwooLucioLee** [swsnu/swpp2020-team13#4]
We might create a separate model for tags.
Either way, we will need to determine API scheme (url patterns) for adding and deleting tags.

Solution 1
(POST) "api/v1/goals/<goal_id>/tag : create a new tag (presumably one by one)
(PUT) "api/v1/goals/<goal_id>/tag/<tag_id> : update a specific tag
(DELETE) "api/v1/goals/<goal_id>/tag/<tag_id> : delete a specific tag

Solution 2
(POST) "api/v1/tags : create a new tag (a goal id is included in the request body)
(PUT) "api/v1/tags/<tag_id> : update a specific tag (a goal id is stored in a tag instance)
(DELETE) "api/v1/tags/<tag_id> : delete a specific tag (a goal id is stored in a tag instance)

Which one looks better?

**Comment by jiyewise** [comment]
I prefer solution 1, as the tags are goal-specific. What would be the fields for tag model? When the details are set, I will start implementing tag CRUD. Thanks for your suggestion! :)

**Comment by ChanwooLucioLee** [comment]
There is a library called django-taggit and we are going to use it. I will take care of that.
The fields of Tag model will look like below:
{ id: number, tags: <handled by django-taggit>, goal: foreign key, user: foreign key }

You can give suggestions if you want to add or change the signature of Tag model.

**Comment by jiyewise** [comment]
@ChanwooLucioLee Didn't know there was a taggit library..! Could you please take care of tag implementation then, as you're more familiar with it? I think the fields of tag model is fine now. If I have other suggestions later on, I would open a issue regarding the suggestion. Thanks!

**Comment by ChanwooLucioLee** [comment]
@jiyewise Got it.
