### ISSUE TITLE
The achievement is displayed in the order it is added, not in chronological order

### ISSUE THREAD

**Issue by songbird39** [swsnu/swpp2020-team13#41]
In the ACHIEVEMENT JOURNAL, the achievement is displayed in the order it is added, not in chronological order. This may not be a problem when the user adds the achievement for that day only, but since it is allowed to add past achievements...

**Comment by jiyewise** [comment]
달력에서 예전 날짜를 선택하면 그 날짜에 해당하는 achievement가 기록되게 기능이 구현이 되어 있고요, journal에서는 단순히 정렬 문제인 것 같습니다
