### ISSUE TITLE
The next page button doesn't work in goal card display

### ISSUE THREAD

**Issue by songbird39** [swsnu/swpp2020-team13#42]
![image](https://user-images.githubusercontent.com/50364722/101663312-e6af9b00-3a8d-11eb-9b63-f8e1ccc33f21.png)
On the dashboard page, if the user has more than 6 goals the next page button should display the next 6 goals. This doesn't work with the error message on console (on screenshot)

**Comment by jiyewise** [comment]
this.state가 빠져서 난 에러였습니다
