### ISSUE TITLE
The upload button for photo doesn't do anything?

### ISSUE THREAD

**Issue by songbird39** [swsnu/swpp2020-team13#43]
Although there is an upload button under the photo attaching, clicking the button doesn't produce any effect. Submitting the form without clicking upload seems to work without any problems, so I was just wondering what this button was supposed to do?

**Comment by jiyewise** [comment]
네 아무것도 안합니다

**Comment by jiyewise** [comment]
upload버튼은 아무것도 안해서 삭제하고 프리뷰를 추가했습니다
