### ISSUE TITLE
The goal images are not updated after clicking the next page button

### ISSUE THREAD

**Issue by songbird39** [swsnu/swpp2020-team13#47]
![image](https://user-images.githubusercontent.com/50364722/101747873-22d71000-3b0f-11eb-82de-950075cabe11.png)
![image](https://user-images.githubusercontent.com/50364722/101747893-29fe1e00-3b0f-11eb-852b-6cbc515075cf.png)
![image](https://user-images.githubusercontent.com/50364722/101747928-34201c80-3b0f-11eb-95cf-806beddfa263.png)
Clicking the next page button updates the goal names, but not the goal images. This is not the problem of the data itself, since the images are rendered correctly when on the edit goal page, and when the goal order changes due to edit/add. (Before editing the oil painting goal, the pottery goal was there and had the knitting image. But after the order is changed the pottery goal has its own proper image now.)

**Comment by jiyewise** [comment]
저거는 프론트 문제가 아니라 크롬에서 이미지를 캐시하기 때문에 벌어지는 일인 것 같습니다
