### ISSUE TITLE
JSON format for Goal CRUD 

### ISSUE THREAD

**Issue by jiyewise** [swsnu/swpp2020-team13#8]
What would be JSON response format for GET/POST/PUT in Goal CRUD?
While implementation, I have arbitarily set the JSON format as:
1. For goalList(/goals/) : GET : list of `` {'title': goal.title, 'photo': goal.photo, 'user': goal.user.id}``
2. For goalList(/goals/) : POST : `{'title': new_goal.title, 'photo': new_goal.photo, 'user': new_goal.user.id}`
3. For goalDetail(/goals/:id) : GET :  `{'title': goal.title, 'photo': goal.photo, 'user': goal.user.id, 'created_at': str(goal.created_at) }`
4. For goalDetail(/goals/:id) : PUT: `{'title': goal.title, 'photo': goal.photo, 'user': goal.user.id, 'created_at': str(goal.created_at), 'updated_at': str(goal.updated_at)}`
Is there ideas or suggestions regarding JSON response format?
Thanks!

**Comment by ChanwooLucioLee** [comment]
@jiyewise Your question is exactly what I was asking in Issue #6 (Frontend Redux Store and Reducers Design) because response.data from backend will be dispatched to the redux store in frontend. We have to design JSON response format for Goal, Task, and Achievement CRUD.
